### ISSUE TITLE
Training device

### ISSUE THREAD

**Issue by APotatoBoy** [maciej-sypetkowski/kaggle-rcic-1st#1]
Congratulations on your great score in the competition and thanks for your solutions.

When I tried to run your code , I found that the model can only run in one NVIDIA device, other devices were spare.
What devices did you use and how long did it take to train?

**Comment by maciej-sypetkowski** [comment]
This code doesn't have multi-GPU support. Because of very limited computing resources I didn't implement it. I trained on NVIDIA Titan V, and for each of 2 commands stated in the README, it took ~100 hours.
