### ISSUE TITLE
Setting gradient update

### ISSUE THREAD

**Issue by njan-creative** [maciej-sypetkowski/kaggle-rcic-1st#2]
I am trying to use the code for another multi-label classification. 
I am getting the below warning. Can you help me with the same.

/opt/conda/lib/python3.7/site-packages/torch/utils/checkpoint.py:25: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")

**Comment by maciej-sypetkowski** [comment]
Can you paste the entire traceback? This warning is coming from memory efficient densenet, and it says that there's no point in checkpointing as all previous parameters don't require gradient. One possible explanation is that you froze some layers of the backbone. Did you do this or change the model architecture in any way?

P.S. this is not a multi-label classification. The model assigns one image to one class.

**Comment by njan-creative** [comment]
Since the input was only normal images, I added an argument args['input_channels'] and set it to 3.
Since there is no s, I had set args['concat_cell_type'] to False
I did not make any other change in the model code. 

The backbone used is args['backbone'] = 'mem-densenet121'

This was the complete output.

"/opt/conda/lib/python3.7/site-packages/torch/utils/checkpoint.py:25: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")"

```
class Model(nn.Module):
    def __init__(self, args):
        super().__init__()

        kwargs = {}
        backbone = args['backbone']
        if backbone.startswith('mem-'):
            kwargs['memory_efficient'] = True
            backbone = backbone[4:]

        print('using backbone :: ', backbone)

        if backbone.startswith('densenet'):
            channels = 96 if backbone == 'densenet161' else 64
            first_conv = nn.Conv2d(args['input_channels'], channels, 7, 2, 3, bias=False)
            pretrained_backbone = getattr(torchvision.models, backbone)(pretrained=True, **kwargs)
            self.features = pretrained_backbone.features
            self.features.conv0 = first_conv
            features_num = pretrained_backbone.classifier.in_features
        elif backbone.startswith('resnet') or backbone.startswith('resnext'):
            first_conv = nn.Conv2d(args['input_channels'], 64, 7, 2, 3, bias=False)
            pretrained_backbone = getattr(torchvision.models, backbone)(pretrained=True, **kwargs)
            self.features = nn.Sequential(
                first_conv,
                pretrained_backbone.bn1,
                pretrained_backbone.relu,
                pretrained_backbone.maxpool,
                pretrained_backbone.layer1,
                pretrained_backbone.layer2,
                pretrained_backbone.layer3,
                pretrained_backbone.layer4,
            )
            features_num = pretrained_backbone.fc.in_features
        elif backbone.startswith('efficientnet'):
            from efficientnet_pytorch import EfficientNet
            self.efficientnet = EfficientNet.from_pretrained(backbone)
            first_conv = nn.Conv2d(args['input_channels'], self.efficientnet._conv_stem.out_channels, kernel_size=3, stride=2, padding=1, bias=False)
            self.efficientnet._conv_stem = first_conv
            self.features = self.efficientnet.extract_features
            features_num = self.efficientnet._conv_head.out_channels
        else:
            raise ValueError('wrong backbone')

        self.classes = args['classes']
        
        self.concat_cell_type = args['concat_cell_type']
        features_num = features_num + (4 if self.concat_cell_type else 0)

        self.neck = nn.Sequential(
            nn.BatchNorm1d(features_num),
            nn.Linear(features_num, args['embedding_size'], bias=False),
            nn.ReLU(inplace=True),
            nn.BatchNorm1d(args['embedding_size']),
            nn.Linear(args['embedding_size'], args['embedding_size'], bias=False),
            nn.BatchNorm1d(args['embedding_size']),
        )
        self.arc_margin_product = ArcMarginProduct(args['embedding_size'], args['classes'])

        if args['head_hidden'] is None:
            self.head = nn.Linear(args['embedding_size'], args['classes'])
        else:
            self.head = []
            for input_size, output_size in zip([args['embedding_size']] + args['head_hidden'], args['head_hidden']):
                self.head.extend([
                    nn.Linear(input_size, output_size, bias=False),
                    nn.BatchNorm1d(output_size),
                    nn.ReLU(),
                ])
            self.head.append(nn.Linear(args['head_hidden'][-1], args['classes']))
            self.head = nn.Sequential(*self.head)

        for m in self.modules():
            if isinstance(m, nn.BatchNorm1d) or isinstance(m, nn.BatchNorm2d):
                m.momentum = args['bn_mom']

    def embed(self, x, s):
        x = self.features(x)

        x = F.adaptive_avg_pool2d(x, (1, 1))
        x = x.view(x.size(0), -1)
        if self.concat_cell_type:
            x = torch.cat([x, s], dim=1)

        embedding = self.neck(x)
        return embedding

    def metric_classify(self, embedding):
        return self.arc_margin_product(embedding)

    def classify(self, embedding):
        return self.head(embedding)


class ModelAndLoss(nn.Module):
    def __init__(self, args):
        super().__init__()

        self.args = args
        self.model = Model(args)
        self.metric_crit = ArcFaceLoss()
        self.crit = DenseCrossEntropy()

    def train_forward(self, x, s, y):
        embedding = self.model.embed(x, s)

        metric_output = self.model.metric_classify(embedding)
        metric_loss = self.metric_crit(metric_output, y)

        output = self.model.classify(embedding)
        loss = self.crit(output, y)
        print('--- train_forward - loss :: ', loss)
        
        acc = (output.max(1)[1] == y.max(1)[1]).float().mean().item()
        print('--- train_forward - acc :: ', acc)

        coeff = self.args['metric_loss_coeff']
        return loss * (1 - coeff) + metric_loss * coeff, acc

    def eval_forward(self, x, s):
        embedding = self.model.embed(x, s)
        output = self.model.classify(embedding)
        return output

    def embed(self, x, s):
        return self.model.embed(x, s)


class DenseCrossEntropy(nn.Module):
    def forward(self, x, target):
        x = x.float()
        target = target.float()
        logprobs = torch.nn.functional.log_softmax(x, dim=-1)

        loss = -logprobs * target
        loss = loss.sum(-1)
        return loss.mean()


class ArcFaceLoss(nn.modules.Module):
    def __init__(self, s=30.0, m=0.5):
        super().__init__()
        self.crit = DenseCrossEntropy()
        self.s = s
        self.cos_m = math.cos(m)
        self.sin_m = math.sin(m)
        self.th = math.cos(math.pi - m)
        self.mm = math.sin(math.pi - m) * m

    def forward(self, logits, labels):
        logits = logits.float()
        cosine = logits
        sine = torch.sqrt(1.0 - torch.pow(cosine, 2))
        phi = cosine * self.cos_m - sine * self.sin_m
        phi = torch.where(cosine > self.th, phi, cosine - self.mm)
        output = (labels * phi) + ((1.0 - labels) * cosine)
        output *= self.s
        loss = self.crit(output, labels)
        return loss / 2


class ArcMarginProduct(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()
        self.weight = nn.Parameter(torch.FloatTensor(out_features, in_features))
        self.reset_parameters()

    def reset_parameters(self):
        stdv = 1. / math.sqrt(self.weight.size(1))
        self.weight.data.uniform_(-stdv, stdv)

    def forward(self, features):
        cosine = F.linear(F.normalize(features), F.normalize(self.weight))
        return cosine
```

**Comment by maciej-sypetkowski** [comment]
What version of `torch` and `torchvision` do you use? Print `[(name, param.requires_grad) for name, param in model.named_parameters()]` after creating the model. All `requires_grad` should be true. If they are not, then you can set them to true.

**Comment by njan-creative** [comment]
I think the warning were wrong. It showed lots of them being trainable.

The versions are below.
torch==1.5.0
torchvision==0.6.0a0+82fd1c8

Also just wanted to confirm if you trained complete or only few layers in steps.

`%
30.8M/30.8M [00:01<00:00, 16.9MB/s]


[('model.features.conv0.weight', True), ('model.features.norm0.weight', True), ('model.features.norm0.bias', True), ('model.features.denseblock1.denselayer1.norm1.weight', True), ('model.features.denseblock1.denselayer1.norm1.bias', True), ('model.features.denseblock1.denselayer1.conv1.weight', True), ('model.features.denseblock1.denselayer1.norm2.weight', True), ('model.features.denseblock1.denselayer1.norm2.bias', True), ('model.features.denseblock1.denselayer1.conv2.weight', True), ('model.features.denseblock1.denselayer2.norm1.weight', True), ('model.features.denseblock1.denselayer2.norm1.bias', True), ('model.features.denseblock1.denselayer2.conv1.weight', True), ('model.features.denseblock1.denselayer2.norm2.weight', True), ('model.features.denseblock1.denselayer2.norm2.bias', True), ('model.features.denseblock1.denselayer2.conv2.weight', True), ('model.features.denseblock1.denselayer3.norm1.weight', True), ('model.features.denseblock1.denselayer3.norm1.bias', True), ('model.features.denseblock1.denselayer3.conv1.weight', True), ('model.features.denseblock1.denselayer3.norm2.weight', True), ('model.features.denseblock1.denselayer3.norm2.bias', True), ('model.features.denseblock1.denselayer3.conv2.weight', True), ('model.features.denseblock1.denselayer4.norm1.weight', True), ('model.features.denseblock1.denselayer4.norm1.bias', True), ('model.features.denseblock1.denselayer4.conv1.weight', True), ('model.features.denseblock1.denselayer4.norm2.weight', True), ('model.features.denseblock1.denselayer4.norm2.bias', True), ('model.features.denseblock1.denselayer4.conv2.weight', True), ('model.features.denseblock1.denselayer5.norm1.weight', True), ('model.features.denseblock1.denselayer5.norm1.bias', True), ('model.features.denseblock1.denselayer5.conv1.weight', True), ('model.features.denseblock1.denselayer5.norm2.weight', True), ('model.features.denseblock1.denselayer5.norm2.bias', True), ('model.features.denseblock1.denselayer5.conv2.weight', True), ('model.features.denseblock1.denselayer6.norm1.weight', True), ('model.features.denseblock1.denselayer6.norm1.bias', True), ('model.features.denseblock1.denselayer6.conv1.weight', True), ('model.features.denseblock1.denselayer6.norm2.weight', True), ('model.features.denseblock1.denselayer6.norm2.bias', True), ('model.features.denseblock1.denselayer6.conv2.weight', True), ('model.features.transition1.norm.weight', True), ('model.features.transition1.norm.bias', True), ('model.features.transition1.conv.weight', True), ('model.features.denseblock2.denselayer1.norm1.weight', True), ('model.features.denseblock2.denselayer1.norm1.bias', True), ('model.features.denseblock2.denselayer1.conv1.weight', True), ('model.features.denseblock2.denselayer1.norm2.weight', True), ('model.features.denseblock2.denselayer1.norm2.bias', True), ('model.features.denseblock2.denselayer1.conv2.weight', True), ('model.features.denseblock2.denselayer2.norm1.weight', True), ('model.features.denseblock2.denselayer2.norm1.bias', True), ('model.features.denseblock2.denselayer2.conv1.weight', True), ('model.features.denseblock2.denselayer2.norm2.weight', True), ('model.features.denseblock2.denselayer2.norm2.bias', True), ('model.features.denseblock2.denselayer2.conv2.weight', True), ('model.features.denseblock2.denselayer3.norm1.weight', True), ('model.features.denseblock2.denselayer3.norm1.bias', True), ('model.features.denseblock2.denselayer3.conv1.weight', True), ('model.features.denseblock2.denselayer3.norm2.weight', True), ('model.features.denseblock2.denselayer3.norm2.bias', True), ('model.features.denseblock2.denselayer3.conv2.weight', True), ('model.features.denseblock2.denselayer4.norm1.weight', True), ('model.features.denseblock2.denselayer4.norm1.bias', True), ('model.features.denseblock2.denselayer4.conv1.weight', True), ('model.features.denseblock2.denselayer4.norm2.weight', True), ('model.features.denseblock2.denselayer4.norm2.bias', True), ('model.features.denseblock2.denselayer4.conv2.weight', True), ('model.features.denseblock2.denselayer5.norm1.weight', True), ('model.features.denseblock2.denselayer5.norm1.bias', True), ('model.features.denseblock2.denselayer5.conv1.weight', True), ('model.features.denseblock2.denselayer5.norm2.weight', True), ('model.features.denseblock2.denselayer5.norm2.bias', True), ('model.features.denseblock2.denselayer5.conv2.weight', True), ('model.features.denseblock2.denselayer6.norm1.weight', True), ('model.features.denseblock2.denselayer6.norm1.bias', True), ('model.features.denseblock2.denselayer6.conv1.weight', True), ('model.features.denseblock2.denselayer6.norm2.weight', True), ('model.features.denseblock2.denselayer6.norm2.bias', True), ('model.features.denseblock2.denselayer6.conv2.weight', True), ('model.features.denseblock2.denselayer7.norm1.weight', True), ('model.features.denseblock2.denselayer7.norm1.bias', True), ('model.features.denseblock2.denselayer7.conv1.weight', True), ('model.features.denseblock2.denselayer7.norm2.weight', True), ('model.features.denseblock2.denselayer7.norm2.bias', True), ('model.features.denseblock2.denselayer7.conv2.weight', True), ('model.features.denseblock2.denselayer8.norm1.weight', True), ('model.features.denseblock2.denselayer8.norm1.bias', True), ('model.features.denseblock2.denselayer8.conv1.weight', True), ('model.features.denseblock2.denselayer8.norm2.weight', True), ('model.features.denseblock2.denselayer8.norm2.bias', True), ('model.features.denseblock2.denselayer8.conv2.weight', True), ('model.features.denseblock2.denselayer9.norm1.weight', True), ('model.features.denseblock2.denselayer9.norm1.bias', True), ('model.features.denseblock2.denselayer9.conv1.weight', True), ('model.features.denseblock2.denselayer9.norm2.weight', True), ('model.features.denseblock2.denselayer9.norm2.bias', True), ('model.features.denseblock2.denselayer9.conv2.weight', True), ('model.features.denseblock2.denselayer10.norm1.weight', True), ('model.features.denseblock2.denselayer10.norm1.bias', True), ('model.features.denseblock2.denselayer10.conv1.weight', True), ('model.features.denseblock2.denselayer10.norm2.weight', True), ('model.features.denseblock2.denselayer10.norm2.bias', True), ('model.features.denseblock2.denselayer10.conv2.weight', True), ('model.features.denseblock2.denselayer11.norm1.weight', True), ('model.features.denseblock2.denselayer11.norm1.bias', True), ('model.features.denseblock2.denselayer11.conv1.weight', True), ('model.features.denseblock2.denselayer11.norm2.weight', True), ('model.features.denseblock2.denselayer11.norm2.bias', True), ('model.features.denseblock2.denselayer11.conv2.weight', True), ('model.features.denseblock2.denselayer12.norm1.weight', True), ('model.features.denseblock2.denselayer12.norm1.bias', True), ('model.features.denseblock2.denselayer12.conv1.weight', True), ('model.features.denseblock2.denselayer12.norm2.weight', True), ('model.features.denseblock2.denselayer12.norm2.bias', True), ('model.features.denseblock2.denselayer12.conv2.weight', True), ('model.features.transition2.norm.weight', True), ('model.features.transition2.norm.bias', True), ('model.features.transition2.conv.weight', True), ('model.features.denseblock3.denselayer1.norm1.weight', True), ('model.features.denseblock3.denselayer1.norm1.bias', True), ('model.features.denseblock3.denselayer1.conv1.weight', True), ('model.features.denseblock3.denselayer1.norm2.weight', True), ('model.features.denseblock3.denselayer1.norm2.bias', True), ('model.features.denseblock3.denselayer1.conv2.weight', True), ('model.features.denseblock3.denselayer2.norm1.weight', True), ('model.features.denseblock3.denselayer2.norm1.bias', True), ('model.features.denseblock3.denselayer2.conv1.weight', True), ('model.features.denseblock3.denselayer2.norm2.weight', True), ('model.features.denseblock3.denselayer2.norm2.bias', True), ('model.features.denseblock3.denselayer2.conv2.weight', True), ('model.features.denseblock3.denselayer3.norm1.weight', True), ('model.features.denseblock3.denselayer3.norm1.bias', True), ('model.features.denseblock3.denselayer3.conv1.weight', True), ('model.features.denseblock3.denselayer3.norm2.weight', True), ('model.features.denseblock3.denselayer3.norm2.bias', True), ('model.features.denseblock3.denselayer3.conv2.weight', True), ('model.features.denseblock3.denselayer4.norm1.weight', True), ('model.features.denseblock3.denselayer4.norm1.bias', True), ('model.features.denseblock3.denselayer4.conv1.weight', True), ('model.features.denseblock3.denselayer4.norm2.weight', True), ('model.features.denseblock3.denselayer4.norm2.bias', True), ('model.features.denseblock3.denselayer4.conv2.weight', True), ('model.features.denseblock3.denselayer5.norm1.weight', True), ('model.features.denseblock3.denselayer5.norm1.bias', True), ('model.features.denseblock3.denselayer5.conv1.weight', True), ('model.features.denseblock3.denselayer5.norm2.weight', True), ('model.features.denseblock3.denselayer5.norm2.bias', True), ('model.features.denseblock3.denselayer5.conv2.weight', True), ('model.features.denseblock3.denselayer6.norm1.weight', True), ('model.features.denseblock3.denselayer6.norm1.bias', True), ('model.features.denseblock3.denselayer6.conv1.weight', True), ('model.features.denseblock3.denselayer6.norm2.weight', True), ('model.features.denseblock3.denselayer6.norm2.bias', True), ('model.features.denseblock3.denselayer6.conv2.weight', True), ('model.features.denseblock3.denselayer7.norm1.weight', True), ('model.features.denseblock3.denselayer7.norm1.bias', True), ('model.features.denseblock3.denselayer7.conv1.weight', True), ('model.features.denseblock3.denselayer7.norm2.weight', True), ('model.features.denseblock3.denselayer7.norm2.bias', True), ('model.features.denseblock3.denselayer7.conv2.weight', True), ('model.features.denseblock3.denselayer8.norm1.weight', True), ('model.features.denseblock3.denselayer8.norm1.bias', True), ('model.features.denseblock3.denselayer8.conv1.weight', True), ('model.features.denseblock3.denselayer8.norm2.weight', True), ('model.features.denseblock3.denselayer8.norm2.bias', True), ('model.features.denseblock3.denselayer8.conv2.weight', True), ('model.features.denseblock3.denselayer9.norm1.weight', True), ('model.features.denseblock3.denselayer9.norm1.bias', True), ('model.features.denseblock3.denselayer9.conv1.weight', True), ('model.features.denseblock3.denselayer9.norm2.weight', True), ('model.features.denseblock3.denselayer9.norm2.bias', True), ('model.features.denseblock3.denselayer9.conv2.weight', True), ('model.features.denseblock3.denselayer10.norm1.weight', True), ('model.features.denseblock3.denselayer10.norm1.bias', True), ('model.features.denseblock3.denselayer10.conv1.weight', True), ('model.features.denseblock3.denselayer10.norm2.weight', True), ('model.features.denseblock3.denselayer10.norm2.bias', True), ('model.features.denseblock3.denselayer10.conv2.weight', True), ('model.features.denseblock3.denselayer11.norm1.weight', True), ('model.features.denseblock3.denselayer11.norm1.bias', True), ('model.features.denseblock3.denselayer11.conv1.weight', True), ('model.features.denseblock3.denselayer11.norm2.weight', True), ('model.features.denseblock3.denselayer11.norm2.bias', True), ('model.features.denseblock3.denselayer11.conv2.weight', True), ('model.features.denseblock3.denselayer12.norm1.weight', True), ('model.features.denseblock3.denselayer12.norm1.bias', True), ('model.features.denseblock3.denselayer12.conv1.weight', True), ('model.features.denseblock3.denselayer12.norm2.weight', True), ('model.features.denseblock3.denselayer12.norm2.bias', True), ('model.features.denseblock3.denselayer12.conv2.weight', True), ('model.features.denseblock3.denselayer13.norm1.weight', True), ('model.features.denseblock3.denselayer13.norm1.bias', True), ('model.features.denseblock3.denselayer13.conv1.weight', True), ('model.features.denseblock3.denselayer13.norm2.weight', True), ('model.features.denseblock3.denselayer13.norm2.bias', True), ('model.features.denseblock3.denselayer13.conv2.weight', True), ('model.features.denseblock3.denselayer14.norm1.weight', True), ('model.features.denseblock3.denselayer14.norm1.bias', True), ('model.features.denseblock3.denselayer14.conv1.weight', True), ('model.features.denseblock3.denselayer14.norm2.weight', True), ('model.features.denseblock3.denselayer14.norm2.bias', True), ('model.features.denseblock3.denselayer14.conv2.weight', True), ('model.features.denseblock3.denselayer15.norm1.weight', True), ('model.features.denseblock3.denselayer15.norm1.bias', True), ('model.features.denseblock3.denselayer15.conv1.weight', True), ('model.features.denseblock3.denselayer15.norm2.weight', True), ('model.features.denseblock3.denselayer15.norm2.bias', True), ('model.features.denseblock3.denselayer15.conv2.weight', True), ('model.features.denseblock3.denselayer16.norm1.weight', True), ('model.features.denseblock3.denselayer16.norm1.bias', True), ('model.features.denseblock3.denselayer16.conv1.weight', True), ('model.features.denseblock3.denselayer16.norm2.weight', True), ('model.features.denseblock3.denselayer16.norm2.bias', True), ('model.features.denseblock3.denselayer16.conv2.weight', True), ('model.features.denseblock3.denselayer17.norm1.weight', True), ('model.features.denseblock3.denselayer17.norm1.bias', True), ('model.features.denseblock3.denselayer17.conv1.weight', True), ('model.features.denseblock3.denselayer17.norm2.weight', True), ('model.features.denseblock3.denselayer17.norm2.bias', True), ('model.features.denseblock3.denselayer17.conv2.weight', True), ('model.features.denseblock3.denselayer18.norm1.weight', True), ('model.features.denseblock3.denselayer18.norm1.bias', True), ('model.features.denseblock3.denselayer18.conv1.weight', True), ('model.features.denseblock3.denselayer18.norm2.weight', True), ('model.features.denseblock3.denselayer18.norm2.bias', True), ('model.features.denseblock3.denselayer18.conv2.weight', True), ('model.features.denseblock3.denselayer19.norm1.weight', True), ('model.features.denseblock3.denselayer19.norm1.bias', True), ('model.features.denseblock3.denselayer19.conv1.weight', True), ('model.features.denseblock3.denselayer19.norm2.weight', True), ('model.features.denseblock3.denselayer19.norm2.bias', True), ('model.features.denseblock3.denselayer19.conv2.weight', True), ('model.features.denseblock3.denselayer20.norm1.weight', True), ('model.features.denseblock3.denselayer20.norm1.bias', True), ('model.features.denseblock3.denselayer20.conv1.weight', True), ('model.features.denseblock3.denselayer20.norm2.weight', True), ('model.features.denseblock3.denselayer20.norm2.bias', True), ('model.features.denseblock3.denselayer20.conv2.weight', True), ('model.features.denseblock3.denselayer21.norm1.weight', True), ('model.features.denseblock3.denselayer21.norm1.bias', True), ('model.features.denseblock3.denselayer21.conv1.weight', True), ('model.features.denseblock3.denselayer21.norm2.weight', True), ('model.features.denseblock3.denselayer21.norm2.bias', True), ('model.features.denseblock3.denselayer21.conv2.weight', True), ('model.features.denseblock3.denselayer22.norm1.weight', True), ('model.features.denseblock3.denselayer22.norm1.bias', True), ('model.features.denseblock3.denselayer22.conv1.weight', True), ('model.features.denseblock3.denselayer22.norm2.weight', True), ('model.features.denseblock3.denselayer22.norm2.bias', True), ('model.features.denseblock3.denselayer22.conv2.weight', True), ('model.features.denseblock3.denselayer23.norm1.weight', True), ('model.features.denseblock3.denselayer23.norm1.bias', True), ('model.features.denseblock3.denselayer23.conv1.weight', True), ('model.features.denseblock3.denselayer23.norm2.weight', True), ('model.features.denseblock3.denselayer23.norm2.bias', True), ('model.features.denseblock3.denselayer23.conv2.weight', True), ('model.features.denseblock3.denselayer24.norm1.weight', True), ('model.features.denseblock3.denselayer24.norm1.bias', True), ('model.features.denseblock3.denselayer24.conv1.weight', True), ('model.features.denseblock3.denselayer24.norm2.weight', True), ('model.features.denseblock3.denselayer24.norm2.bias', True), ('model.features.denseblock3.denselayer24.conv2.weight', True), ('model.features.transition3.norm.weight', True), ('model.features.transition3.norm.bias', True), ('model.features.transition3.conv.weight', True), ('model.features.denseblock4.denselayer1.norm1.weight', True), ('model.features.denseblock4.denselayer1.norm1.bias', True), ('model.features.denseblock4.denselayer1.conv1.weight', True), ('model.features.denseblock4.denselayer1.norm2.weight', True), ('model.features.denseblock4.denselayer1.norm2.bias', True), ('model.features.denseblock4.denselayer1.conv2.weight', True), ('model.features.denseblock4.denselayer2.norm1.weight', True), ('model.features.denseblock4.denselayer2.norm1.bias', True), ('model.features.denseblock4.denselayer2.conv1.weight', True), ('model.features.denseblock4.denselayer2.norm2.weight', True), ('model.features.denseblock4.denselayer2.norm2.bias', True), ('model.features.denseblock4.denselayer2.conv2.weight', True), ('model.features.denseblock4.denselayer3.norm1.weight', True), ('model.features.denseblock4.denselayer3.norm1.bias', True), ('model.features.denseblock4.denselayer3.conv1.weight', True), ('model.features.denseblock4.denselayer3.norm2.weight', True), ('model.features.denseblock4.denselayer3.norm2.bias', True), ('model.features.denseblock4.denselayer3.conv2.weight', True), ('model.features.denseblock4.denselayer4.norm1.weight', True), ('model.features.denseblock4.denselayer4.norm1.bias', True), ('model.features.denseblock4.denselayer4.conv1.weight', True), ('model.features.denseblock4.denselayer4.norm2.weight', True), ('model.features.denseblock4.denselayer4.norm2.bias', True), ('model.features.denseblock4.denselayer4.conv2.weight', True), ('model.features.denseblock4.denselayer5.norm1.weight', True), ('model.features.denseblock4.denselayer5.norm1.bias', True), ('model.features.denseblock4.denselayer5.conv1.weight', True), ('model.features.denseblock4.denselayer5.norm2.weight', True), ('model.features.denseblock4.denselayer5.norm2.bias', True), ('model.features.denseblock4.denselayer5.conv2.weight', True), ('model.features.denseblock4.denselayer6.norm1.weight', True), ('model.features.denseblock4.denselayer6.norm1.bias', True), ('model.features.denseblock4.denselayer6.conv1.weight', True), ('model.features.denseblock4.denselayer6.norm2.weight', True), ('model.features.denseblock4.denselayer6.norm2.bias', True), ('model.features.denseblock4.denselayer6.conv2.weight', True), ('model.features.denseblock4.denselayer7.norm1.weight', True), ('model.features.denseblock4.denselayer7.norm1.bias', True), ('model.features.denseblock4.denselayer7.conv1.weight', True), ('model.features.denseblock4.denselayer7.norm2.weight', True), ('model.features.denseblock4.denselayer7.norm2.bias', True), ('model.features.denseblock4.denselayer7.conv2.weight', True), ('model.features.denseblock4.denselayer8.norm1.weight', True), ('model.features.denseblock4.denselayer8.norm1.bias', True), ('model.features.denseblock4.denselayer8.conv1.weight', True), ('model.features.denseblock4.denselayer8.norm2.weight', True), ('model.features.denseblock4.denselayer8.norm2.bias', True), ('model.features.denseblock4.denselayer8.conv2.weight', True), ('model.features.denseblock4.denselayer9.norm1.weight', True), ('model.features.denseblock4.denselayer9.norm1.bias', True), ('model.features.denseblock4.denselayer9.conv1.weight', True), ('model.features.denseblock4.denselayer9.norm2.weight', True), ('model.features.denseblock4.denselayer9.norm2.bias', True), ('model.features.denseblock4.denselayer9.conv2.weight', True), ('model.features.denseblock4.denselayer10.norm1.weight', True), ('model.features.denseblock4.denselayer10.norm1.bias', True), ('model.features.denseblock4.denselayer10.conv1.weight', True), ('model.features.denseblock4.denselayer10.norm2.weight', True), ('model.features.denseblock4.denselayer10.norm2.bias', True), ('model.features.denseblock4.denselayer10.conv2.weight', True), ('model.features.denseblock4.denselayer11.norm1.weight', True), ('model.features.denseblock4.denselayer11.norm1.bias', True), ('model.features.denseblock4.denselayer11.conv1.weight', True), ('model.features.denseblock4.denselayer11.norm2.weight', True), ('model.features.denseblock4.denselayer11.norm2.bias', True), ('model.features.denseblock4.denselayer11.conv2.weight', True), ('model.features.denseblock4.denselayer12.norm1.weight', True), ('model.features.denseblock4.denselayer12.norm1.bias', True), ('model.features.denseblock4.denselayer12.conv1.weight', True), ('model.features.denseblock4.denselayer12.norm2.weight', True), ('model.features.denseblock4.denselayer12.norm2.bias', True), ('model.features.denseblock4.denselayer12.conv2.weight', True), ('model.features.denseblock4.denselayer13.norm1.weight', True), ('model.features.denseblock4.denselayer13.norm1.bias', True), ('model.features.denseblock4.denselayer13.conv1.weight', True), ('model.features.denseblock4.denselayer13.norm2.weight', True), ('model.features.denseblock4.denselayer13.norm2.bias', True), ('model.features.denseblock4.denselayer13.conv2.weight', True), ('model.features.denseblock4.denselayer14.norm1.weight', True), ('model.features.denseblock4.denselayer14.norm1.bias', True), ('model.features.denseblock4.denselayer14.conv1.weight', True), ('model.features.denseblock4.denselayer14.norm2.weight', True), ('model.features.denseblock4.denselayer14.norm2.bias', True), ('model.features.denseblock4.denselayer14.conv2.weight', True), ('model.features.denseblock4.denselayer15.norm1.weight', True), ('model.features.denseblock4.denselayer15.norm1.bias', True), ('model.features.denseblock4.denselayer15.conv1.weight', True), ('model.features.denseblock4.denselayer15.norm2.weight', True), ('model.features.denseblock4.denselayer15.norm2.bias', True), ('model.features.denseblock4.denselayer15.conv2.weight', True), ('model.features.denseblock4.denselayer16.norm1.weight', True), ('model.features.denseblock4.denselayer16.norm1.bias', True), ('model.features.denseblock4.denselayer16.conv1.weight', True), ('model.features.denseblock4.denselayer16.norm2.weight', True), ('model.features.denseblock4.denselayer16.norm2.bias', True), ('model.features.denseblock4.denselayer16.conv2.weight', True), ('model.features.norm5.weight', True), ('model.features.norm5.bias', True), ('model.neck.0.weight', True), ('model.neck.0.bias', True), ('model.neck.1.weight', True), ('model.neck.3.weight', True), ('model.neck.3.bias', True), ('model.neck.4.weight', True), ('model.neck.5.weight', True), ('model.neck.5.bias', True), ('model.arc_margin_product.weight', True), ('model.head.weight', True), ('model.head.bias', True)]
`

**Comment by maciej-sypetkowski** [comment]
In every step I always train all weights.
